### ISSUE TITLE
I'm unable to launch BL2 correctly

### ISSUE THREAD

**Issue by AvoidAtAllCosts** [c0dycode/BL-AutoexecDLL#1]
I decided to play BL2 again after a hiatus of a couple of months and after factory resetting my PC and came across your AutoExec mod. I've ran into some issues with BL2 in the past few days (crashes and game-breaking bugs at random times) so I decided to start the installation of BL2 from scratch. 

After installing the game via steam, it launched perfectly fine. I also added "-nostartupmovies" & "-nolauncher" to my BL2 launch options on Steam, the game still launched seamlessly. I then installed Reshade for BL2, the game still had no problems launching. Next up was the Filtertool along with the UCP (which was named Patch.txt), the game launched without a hitch.

I then added a 'autoexec.txt' file (with "exec Patch.txt" as only content) to Borderlands 2/Binaries. I added the 'PhysXExtensions.dll' file from the 'AutoExecNoGravity' folder along with the 'PhysXExtensions_org.dll' file that was in the main folder (I did not rename the original 'PhysXExtensions.dll' file in my Borderlands 2/Binaries/Win32 folder) to Borderlands 2/Binaries/Win32 and chose to overwrite the original 'PhysXExtensions.dll'.

When I attempted to launch BL2 via Steam, it briefly said "running" next to Borderlands 2 in the list of downloaded games but then vanished. When I tried executing 'Borderlands 2.exe' (via Administrator) an error message showed up and said the files 'MSVCP140.dll' & 'VCRUNTIME140.dll' are missing. After a quick Google search I downloaded these 2 files manually and added them to the correct folders (C:/Windows/SYSWOW64 & C:/Windows/System32). 

The game did launch this time but after playing for an hour the game crashed (the apparently infamous "Fatal Error!" crash) but I haven't yet pinned down what the cause of this crash is (I have been able to play 260+ hours of BL2 on this exact PC before so it can't be my specs. Nor can it be the Filtertool or ReShade since I used these before too without the game crashing. I also meet all software requirements of BL2's Steam page).

I just wanted to bring this to your attention just in case. My apologies if these launch issues appear to be caused by an oversight on my part.

**Comment by c0dycode** [comment]
There have been a few people reporting random crashes. Usually on changing maps for example.
Unfortunately I can't reproduce them on my system. However, someone told me that an older version seemed to work fine.

So undo the changes with the Physx-dll (delete the PhysXExtensions.dll and rename the PhysXExtensions_org.dll to PhysXExtensions.dll) and then try this version:

https://github.com/c0dycode/BL-AutoexecDLL/blob/529ee14bd28b3b2627b28b8edbb8b31b2c70665c/BL2%20DLL-Autoexec%20Alpha%20v-12.1.zip

Installation is basically the same as with this one. Otherwise take a look at the included readme. 👍 

If the game doesn't launch via steam, launch it via the exe. After that it should ™️ work fine again via steam.

I'm currently focusing on fixing those issues, though it's difficult when I can't properly reproduce them.

**Comment by AvoidAtAllCosts** [comment]
I may just have found out how to make my game crash, but I highly doubt it is related to this mod. For some reason, by going to a vending machine (I used the one in Marcus' shop in Sanctuary both times to let my game crash). When I hover over ammo or the weapon of the day with my cursor it doesn't highlight them. If I click anything in the store, it doesn't respond. I can exit the vending machine and enter it again but it won't let me buy things with my mouse, only when I use my arrow keys to select what I want to purchase and press enter to purchase the item.

The way I can make my game crash is by going to my inventory after exiting the vending machine and the same bug will occur (can't select weapons & I can't favourite them. Only my keyboard functions). If I then proceed to hold my left mouse button and start clicking weapons in my backpack with my right mouse button, the sound will soon start to stutter and the game will crash.
